# Generated by Django 6.0.3 on 2026-03-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_profile',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile/'),
        ),
    ]
